# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------


QT       += core
QT       += gui
QT       += sql
 
greaterThan(QT_MAJOR_VERSION, 5): QT += widgets
 
TEMPLATE = app
TARGET = Inventory
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Inventory.pri)
